### Site settings
lang: ja
title: "こうじのがく書庫： 自作OS、クラウド、ホームページ作成"
description: "とりあえず書庫。ブログには置けない記事を置いときます。"
author: "こうじのがく"
baseurl: ""
exclude: [ "README.md", "LICENSE" ]
url: "http://koujinogaku.github.io"
hostname: "koujinogaku.github.io"
#email: your-email@domain.com
twitter_username: koujinogaku
github_username:  koujinogaku
google_analytics_id: "UA-12321104-3"
google_site_verification: "Y_CUXnqg1e0dvcLIwrJaEkDIKkaiJYj3TqgTuwwlAYY"
google_custom_search_engine_id: "012660066390906066162:koziiwlrg38"
disqus_shortname: koujinogaku

### Build settings
permalink: "/blog/:year/:month/:day/:title/"
images_path: "/img/"
sass:
  style: :compressed
#markdown: kramdown
#gems: [jekyll-test-plugin, jekyll-jsonify, jekyll-assets]

### Appearance
appearance:
  theme: koujinogaku
  ###
  ### Example to enable a wallpaper.
  ###
  #header_text_color: "brown"
  #header_image: none
  #wallpaper_image: /assets/themes/default/img/wallpaper.png
  #wallpaper_repeat: repeat
  #navbar_style: navbar-default navbar-fixed-top

### Blog
paginate: 5
paginate_path: "blog/page:num/" # DON'T TOUCH THIS PATH.
blog:
  title: "こうじのがく : 映画、コンピュータ、旅行、おいしいもの"
  description: "聞いたこと見たこと感じたこと、とりあえず書いときます。"
  title_position: article
  enable_author: true
  comment: true
  share: true
  category: true
  theme: koujinogaku-blog

### Navigation Bar
navbar:
  menu:
    - { caption: "オリジナルOS作り", link: "/os-dev/"}
    - { caption: "EC2/S3の使い方", link: "/amazon-ec2/"}
    - { caption: "ホームページ作り", link: "/web-craft/"}
    - { caption: "PHP", link: "/php/"}
    - { caption: "Android", link: "/android/"}
    - caption: "その他"
      menu:
      - { caption: "その他プロジェクト概要", link: "/projects/"}
      - { caption: "日記", link: "/blog/" }
      - { caption: "Sitemap", link: "/sitemap/" }
      - { caption: "About", link: "/about/" }

### Document collections
collections:
  os-dev:
    title: "オリジナルOS作り(自作OS)"
    description: "オリジナルのOSをカーネルから作っています。"
    output: true
    share: true
    #comment: true
    #theme: koujinogaku-osdev
  amazon-ec2:
    title: "Amazon EC2/S3の使い方(EC2)"
    description: "EC2初心者が、試行錯誤をしながら、何とか動くまでに行なったさまざまな作業と、気づいた点をまとめていきます。"
    output: true
    share: true
    #comment: true
  web-craft:
    title: "ホームページ作り(ホムつく)"
    description: "ホームページ作りをはじめました。"
    output: true
    share: true
    #comment: true
  php:
    title: "PHPプログラミング(PHP)"
    description: "PHPでプログラム書いたときのメモを置いておきます。"
    output: true
    share: true
    #comment: true
  android:
    title: "Android-SDK(Android)"
    description: "Android-SDKをちょっと触ってみたかっただけです。"
    output: true
    share: true
    #comment: true
